version: "3.6"
services:
  server:
    build: .
    container_name: streaming-server
    working_dir: /home/streaming-server
    ports:
      - "8035:8035"
      - "1935:1935"
      - "5540:5544"
    command: >
      bash -c "npm install && npm run start"
    restart: always
    volumes:
      - ./:/home/streaming-server
      - ./node_modules:/home/streaming-server/node_modules

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
